# Generated by Django 5.2 on 2025-04-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_habitacion', models.CharField(choices=[('sencilla', 'Sencilla'), ('doble', 'Doble'), ('triple', 'Triple')], max_length=20)),
                ('numero_habitacion', models.IntegerField(unique=True)),
                ('precio', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='habitaciones/')),
            ],
        ),
    ]
