# Generated by Django 5.2 on 2025-04-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.TimeField(default='14:00')),
                ('check_out_time', models.TimeField(default='12:00')),
                ('late_check_out_fee', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('require_id', models.BooleanField(default=True)),
                ('require_credit_card', models.BooleanField(default=True)),
                ('max_advance_booking_days', models.IntegerField(default=90)),
                ('cancellation_policy_hours', models.IntegerField(default=24)),
                ('min_advance_booking_hours', models.IntegerField(default=24)),
                ('breakfast_included', models.BooleanField(default=True)),
                ('breakfast_price', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
    ]
