# Generated by Django 5.2 on 2025-04-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
